# **Atividade II - Análise Exploratória de Dados**

## **1 Importar bibliotecas e dados**

### 1.1 Importação de bibliotecas

In [11]:
# Importando bibliotecas necessárias
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print("Bibliotecas importadas com sucesso!")

Bibliotecas importadas com sucesso!

### 1.2 Importação de dados

In [12]:
# Caminho do arquivo CSV
CAMINHO_ARQUIVO = r"..\data\469001_Chuvas.csv"
print("Caminho do arquivo CSV definido")

Caminho do arquivo CSV definido

In [13]:
# Criação do dataFrame inicial a partir do arquivo CSV
df = pd.read_csv(CAMINHO_ARQUIVO, skiprows=14, sep=';', decimal=',', encoding='latin1')
print("DataFrame inicial criado com sucesso!")

# Visualizando as primeiras linhas do DataFrame (função head())
print("\nExibindo as primeiras linhas do DataFrame inicial:")
df.head()

DataFrame inicial criado com sucesso!

Exibindo as primeiras linhas do DataFrame inicial:

,EstacaoCodigo,NivelConsistencia,Data,TipoMedicaoChuvas,Maxima,Total,DiaMaxima,NumDiasDeChuva,MaximaStatus,TotalStatus,...,Chuva22Status,Chuva23Status,Chuva24Status,Chuva25Status,Chuva26Status,Chuva27Status,Chuva28Status,Chuva29Status,Chuva30Status,Chuva31Status
0,469001,1,01/12/2025,1,190.3,498.6,2.0,25.0,1,1,...,1,1,1,1,1,1,1,1,1,1
1,469001,1,01/11/2025,1,112.5,330.3,23.0,17.0,1,1,...,1,1,1,1,1,1,1,1,1,0
2,469001,1,01/10/2025,1,33.5,205.2,1.0,20.0,1,1,...,1,1,1,1,1,1,1,1,1,1
3,469001,1,01/09/2025,1,66.5,264.0,26.0,16.0,1,1,...,1,1,1,1,1,1,1,1,1,0
4,469001,1,01/08/2025,1,39.0,82.0,6.0,10.0,1,1,...,1,1,1,1,1,1,1,1,1,1

In [14]:
# Cópia de segurança do DataFrame original
df_original = df.copy()
print("Cópia de segurança do DataFrame original criada com sucesso!")

Cópia de segurança do DataFrame original criada com sucesso!

## **2 Estrutura da Base de Dados**

### 2.1 Tamanho do DataFrame

In [43]:
# Tamanho do DataFrame
print("Tamanho do DataFrame")
print(f"Qtd. linhas: {df.shape[0]} linhas")
print(f"Qtd. colunas: {df.shape[1]} colunas")

Tamanho do DataFrame
Qtd. linhas: 500 linhas
Qtd. colunas: 75 colunas

### 2.2 Propriedades das Colunas

In [44]:
# Nome das colunas
print("Nome das Colunas:")
lista_colunas = df.columns.tolist()
print(lista_colunas)

Nome das Colunas:
['EstacaoCodigo', 'NivelConsistencia', 'Data', 'TipoMedicaoChuvas', 'Maxima', 'Total', 'DiaMaxima', 'NumDiasDeChuva', 'MaximaStatus', 'TotalStatus', 'NumDiasDeChuvaStatus', 'TotalAnual', 'TotalAnualStatus', 'Chuva01', 'Chuva02', 'Chuva03', 'Chuva04', 'Chuva05', 'Chuva06', 'Chuva07', 'Chuva08', 'Chuva09', 'Chuva10', 'Chuva11', 'Chuva12', 'Chuva13', 'Chuva14', 'Chuva15', 'Chuva16', 'Chuva17', 'Chuva18', 'Chuva19', 'Chuva20', 'Chuva21', 'Chuva22', 'Chuva23', 'Chuva24', 'Chuva25', 'Chuva26', 'Chuva27', 'Chuva28', 'Chuva29', 'Chuva30', 'Chuva31', 'Chuva01Status', 'Chuva02Status', 'Chuva03Status', 'Chuva04Status', 'Chuva05Status', 'Chuva06Status', 'Chuva07Status', 'Chuva08Status', 'Chuva09Status', 'Chuva10Status', 'Chuva11Status', 'Chuva12Status', 'Chuva13Status', 'Chuva14Status', 'Chuva15Status', 'Chuva16Status', 'Chuva17Status', 'Chuva18Status', 'Chuva19Status', 'Chuva20Status', 'Chuva21Status', 'Chuva22Status', 'Chuva23Status', 'Chuva24Status', 'Chuva25Status', 'Chuva26Status', 'Chuva27Status', 'Chuva28Status', 'Chuva29Status', 'Chuva30Status', 'Chuva31Status']

In [45]:
# Visualização dos tipos de dados
print("Tipos de Dados por Coluna:")
df.dtypes

Tipos de Dados por Coluna:

EstacaoCodigo          int64
NivelConsistencia      int64
Data                     str
TipoMedicaoChuvas      int64
Maxima               float64
                      ...
Chuva27Status          int64
Chuva28Status          int64
Chuva29Status          int64
Chuva30Status          int64
Chuva31Status          int64
Length: 75, dtype: object

### 2.3 Exemplos de registros

In [46]:
# Exemplos de registros
print("Exibindo as primeiras linhas do DataFrame:")
df.head()

Exibindo as primeiras linhas do DataFrame:

,EstacaoCodigo,NivelConsistencia,Data,TipoMedicaoChuvas,Maxima,Total,DiaMaxima,NumDiasDeChuva,MaximaStatus,TotalStatus,...,Chuva22Status,Chuva23Status,Chuva24Status,Chuva25Status,Chuva26Status,Chuva27Status,Chuva28Status,Chuva29Status,Chuva30Status,Chuva31Status
0,469001,1,01/12/2025,1,190.3,498.6,2.0,25.0,1,1,...,1,1,1,1,1,1,1,1,1,1
1,469001,1,01/11/2025,1,112.5,330.3,23.0,17.0,1,1,...,1,1,1,1,1,1,1,1,1,0
2,469001,1,01/10/2025,1,33.5,205.2,1.0,20.0,1,1,...,1,1,1,1,1,1,1,1,1,1
3,469001,1,01/09/2025,1,66.5,264.0,26.0,16.0,1,1,...,1,1,1,1,1,1,1,1,1,0
4,469001,1,01/08/2025,1,39.0,82.0,6.0,10.0,1,1,...,1,1,1,1,1,1,1,1,1,1

**Interpretação:**

**O que cada linha representa:** Cada linha é um **mês** de dados da estação pluviométrica 469001.

**Principais variáveis:**
- `NivelConsistencia`: qualidade dos dados (1 - Bruto, 2 - Consistido)
- `Data`: mês e ano da medição
- `Maxima`: maior chuva em um único dia no mês (mm)
- `Total`: total de chuva no mês (mm)
- `DiaMaxima`: o dia do mês em que ocorreu a maior precipitação
- `NumDiasDeChuva`: quantos dias choveu no mês
- `Chuva01` a `Chuva31`: chuva diária (mm)

## **3 Qualidade dos dados**

**Instrução:**\
Verificar valores ausentes, duplicatas, tipos incorretos, valores inconsistentes e valores extremos

### 3.1 Verificação de valores ausentes

In [61]:
# Verificação de valores ausentes
print("Valores ausentes por coluna:")
print(df.isnull().sum())

# Registro de colunas com valores ausentes
col_valores_ausentes = df.columns[df.isnull().any()].tolist()
print("\nResumo: Colunas - valores ausentes:")
print(f"Nome das colunas: {col_valores_ausentes}")
print(f"Total: {len(col_valores_ausentes)}")

Valores ausentes por coluna:
EstacaoCodigo         0
NivelConsistencia     0
Data                  0
TipoMedicaoChuvas     0
Maxima               26
                     ..
Chuva27Status         0
Chuva28Status         0
Chuva29Status         0
Chuva30Status         0
Chuva31Status         0
Length: 75, dtype: int64

Resumo: Colunas - valores ausentes:
Nome das colunas: ['Maxima', 'Total', 'DiaMaxima', 'NumDiasDeChuva', 'TotalAnual', 'Chuva01', 'Chuva02', 'Chuva03', 'Chuva04', 'Chuva05', 'Chuva06', 'Chuva07', 'Chuva08', 'Chuva09', 'Chuva10', 'Chuva11', 'Chuva12', 'Chuva13', 'Chuva14', 'Chuva15', 'Chuva16', 'Chuva17', 'Chuva18', 'Chuva19', 'Chuva20', 'Chuva21', 'Chuva22', 'Chuva23', 'Chuva24', 'Chuva25', 'Chuva26', 'Chuva27', 'Chuva28', 'Chuva29', 'Chuva30', 'Chuva31']
Total: 36

### 3.2 Verificação de linhas duplicadas

In [66]:
# Verificação de linhas duplicadas
print("\nVerificação de linhas duplicadas:")
num_linhas_duplicadas = df.duplicated().sum()
print(f"Número de linhas duplicadas: {num_linhas_duplicadas}")

# Flag de verificação de linhas duplicadas
linhas_duplicadas = False
if num_linhas_duplicadas > 0:
    linhas_duplicadas = True
print("\nFlag de verificação de linhas duplicadas criada com sucesso!")

Verificação de linhas duplicadas:
Número de linhas duplicadas: 0

Flag de verificação de linhas duplicadas criada com sucesso!

### 3.3 Verificação de tipos incorretos

**Nota:** A verificação será efetuada apenas nas colunas de interesse

In [68]:
colunas_chuva = lista_colunas[13:44]
colunas_interesse = ['Data', 'Maxima', 'Total', 'NumDiasDeChuva'] + colunas_chuva
print(f"Colunas de chuva: {colunas_chuva}")
print(f"Colunas de interesse: {colunas_interesse}")

Colunas de chuva: ['Chuva01', 'Chuva02', 'Chuva03', 'Chuva04', 'Chuva05', 'Chuva06', 'Chuva07', 'Chuva08', 'Chuva09', 'Chuva10', 'Chuva11', 'Chuva12', 'Chuva13', 'Chuva14', 'Chuva15', 'Chuva16', 'Chuva17', 'Chuva18', 'Chuva19', 'Chuva20', 'Chuva21', 'Chuva22', 'Chuva23', 'Chuva24', 'Chuva25', 'Chuva26', 'Chuva27', 'Chuva28', 'Chuva29', 'Chuva30', 'Chuva31']
Colunas de interesse: ['Data', 'Maxima', 'Total', 'NumDiasDeChuva', 'Chuva01', 'Chuva02', 'Chuva03', 'Chuva04', 'Chuva05', 'Chuva06', 'Chuva07', 'Chuva08', 'Chuva09', 'Chuva10', 'Chuva11', 'Chuva12', 'Chuva13', 'Chuva14', 'Chuva15', 'Chuva16', 'Chuva17', 'Chuva18', 'Chuva19', 'Chuva20', 'Chuva21', 'Chuva22', 'Chuva23', 'Chuva24', 'Chuva25', 'Chuva26', 'Chuva27', 'Chuva28', 'Chuva29', 'Chuva30', 'Chuva31']

In [ ]:
print("Qualidade dos dados")

# Verificação de valores ausentes
print("\nValores ausentes por coluna:")
print(df.isnull().sum())

# Verificação de linhas duplicadas
print(f"\nLinhas duplicadas: {df.duplicated().sum()}")

# Verificação de tipos incorretos de dados (colunas principais)
print("\nTipos de dados incorretos:")
colunas_principais = ['Data', 'Maxima','Total', 'NumDiasDeChuva']
for coluna in colunas_principais:
    print(f"   - '{coluna}': {df[coluna].dtype} (exemplo: {df[coluna].iloc[0]})")

# Verificação de valores inconsistentes
print("\nValores únicos em colunas categóricas:")
print(f"   - 'NivelConsistencia': {df['NivelConsistencia'].unique()}")
if 'TipoMedicaoChuvas' in df.columns:
    print(f"   - 'TipoMedicaoChuvas': {df['TipoMedicaoChuvas'].unique()}")

# Valores extremos - estatística descritiva
print("\nEstatística descritiva p/ encontrar valores extremos:")
colunas_numericas = ['Maxima', 'Total', 'NumDiasDeChuva']
print(df[colunas_numericas].describe())

## **4. Tratamento dos Dados**

In [ ]:
print("Tratamento dos Dados")

# Remoção de duplicatas
if df.duplicated().sum() > 0:
    df = df.drop_duplicates()
    print(f"\nDuplicatas removidas. Shape atual: {df.shape}")
else:
    print("\nNão havia duplicatas para remover.")

# Dados diários de chuva

# Converter a coluna 'Data' para o tipo datetime
df['Data'] = pd.to_datetime(df['Data'], format='%d/%m/%Y')
print("\nColuna 'Data' convertida para o tipo datetime com sucesso!")

# Criar DataFrame com dados diários de chuva
colunas_chuva = [f'Chuva{i:02d}' for i in range(1,32)]
df_diario = df[['Data', 'NivelConsistencia'] + colunas_chuva].copy()
print("\nDataFrame diário criado com sucesso!")
print(f"   Shape: {df_diario.shape}")
#df_diario.head()

# Triagem: Linhas com dados e linhas sem dados
linhas_com_dados = df_diario[colunas_chuva].notna().any(axis=1)
linhas_sem_dados = ~linhas_com_dados
print(f"\nLinhas com dados de chuva: {linhas_com_dados.sum()}")
print(f"Linhas sem dados de chuva: {linhas_sem_dados.sum()}")

# Tratar linhas com dados
def dias_no_mes(data):
    '''
    Retorna o número de dias no mês da data fornecida.
    '''
    ano = data.year
    mes = data.month
    if mes == 2:
        if (ano % 4 == 0 and ano % 100 != 0) or (ano % 400 == 0):
            return 29
        else:
            return 28
    elif mes in [4, 6, 9, 11]:
        return 30
    else:
        return 31

# Aplicando preenchimento nas linhas com dados
for idx in df_diario[linhas_com_dados].index:
    data_mes = df_diario.loc[idx, 'Data']
    num_dias = dias_no_mes(data_mes)
    colunas_validas = [f'Chuva{i:02d}' for i in range(1, num_dias + 1)]
    valores = df_diario.loc[idx, colunas_validas]
    mediana = valores.median()
    df_diario.loc[idx, colunas_validas] = valores.fillna(mediana)

print("\nPreenchimento de valores ausentes nas linhas com dados concluído.")
print('   - Linhas sem dados permanecem com NaN no DataFrame diario.')

# Calcular Maxima, Total e NumDiasDeChuva a partir do df_diario
df_diario['Maxima_calculada'] = df_diario[colunas_chuva].max(axis=1)
df_diario['Total_calculado'] = df_diario[colunas_chuva].sum(axis=1)
df_diario['NumDiasDeChuva_calculado'] = (df_diario[colunas_chuva] > 0).sum(axis=1)
print("\nMaxima, Total e NumDiasDeChuva recalculados a partir do DataFrame diário.")

# Criação do DataFrame ajustado
df_ajustado = df.copy()

# Atualizar Maxima, Total e NumDiasDeChuva
df_ajustado['Maxima'] = df_diario['Maxima_calculada']
df_ajustado['Total'] = df_diario['Total_calculado']
df_ajustado['NumDiasDeChuva'] = df_diario['NumDiasDeChuva_calculado']

# Preencher linhas sem dados com mediana das colunas
mediana_maxima = df_ajustado['Maxima'].median()
mediana_total = df_ajustado['Total'].median()
mediana_dias = df_ajustado['NumDiasDeChuva'].median()

df_ajustado.loc[linhas_sem_dados, 'Maxima'] = mediana_maxima
df_ajustado.loc[linhas_sem_dados, 'Total'] = mediana_total
df_ajustado.loc[linhas_sem_dados, 'NumDiasDeChuva'] = mediana_dias

print("\nDataFrame ajustado criado com sucesso!")
print("   - Linhas sem dados: preenchidas com mediana")
print(f"      - Maxima: {mediana_maxima:.1f}")
print(f"      - Total: {mediana_total:.1f}")
print(f"      - NumDiasDeChuva: {mediana_dias:.1f}")
print(f"   - Shape final: {df_ajustado.shape}")

# Verificação final do DataFrame ajustado
print("\nVerificação final - Valores ausentes nas colunas principais:")
print(df_ajustado[['Maxima', 'Total', 'NumDiasDeChuva']].isnull().sum())

## **5. Utilizando as funções da biblioteca Pandas**

### 5.1 Funções head() e tail()

In [ ]:
# Função head()
print("\nExibindo as primeiras linhas do DataFrame ajustado:")
df_ajustado.head()